"""
Event and alert data models.

Represents system events generated by agents, including
crowd alerts, routing changes, and staff notifications.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional


class EventSeverity(str, Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


class EventType(str, Enum):
    """Classification of system events."""
    CROWD_ALERT = "crowd_alert"
    ROUTE_CHANGE = "route_change"
    FACILITY_UPDATE = "facility_update"
    STAFF_DISPATCH = "staff_dispatch"
    SYSTEM_STATUS = "system_status"
    EVACUATION = "evacuation"
    WAIT_TIME_UPDATE = "wait_time_update"


@dataclass
class Event:
    """
    A system event generated by an agent or service.

    Events flow through the shared memory bus and are consumed
    by the OrchestraAgent for coordination and logging.
    """
    id: str
    event_type: EventType
    severity: EventSeverity
    source_agent: str
    title: str
    message: str
    zone_id: Optional[str] = None
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    is_resolved: bool = False

    def to_dict(self) -> dict:
        """Serialize event for API and WebSocket broadcast."""
        return {
            "id": self.id,
            "event_type": self.event_type.value,
            "severity": self.severity.value,
            "source_agent": self.source_agent,
            "title": self.title,
            "message": self.message,
            "zone_id": self.zone_id,
            "metadata": self.metadata,
            "timestamp": self.timestamp.isoformat(),
            "is_resolved": self.is_resolved,
        }
